[package]
name = "pokerd-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
rand = { version = "0.9.0", features = ["log"] }
serde = { version = "1.0.218", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
